version: '3'

services:
  web:
    build: .
    container_name: longroot_multi_sig_wallet
    command: |
      bash -c "cd /usr/src/app
      npm install
      grunt"
    volumes:
      - .:/usr/src/app:cached
    ports:
      - "8282:8282"
